# Generated by Django 5.0.4 on 2024-04-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                ("date_of_birth", models.DateField(max_length=11, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("United Kingdom", "United Kingdom"),
                            ("United Sates Of America", "United States Of America"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Oyo", "Oyo"),
                            ("Abia", "Abia"),
                            ("Osun", "Osun"),
                            ("Lagos", "Lagos"),
                            ("Kano", "Kano"),
                            ("Abuja", "Abuja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "particulars",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Chairman", "Chairman"),
                            ("Director", "Director"),
                            ("Supervisor", "Supervisor"),
                            ("Admin", "Admin"),
                            ("Delivery Agent", "Delivery Agent"),
                            ("Store Keeper", "Store Keeper"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorce", "Complicated"),
                            ("Complicated", "Complicated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
